### ISSUE TITLE
Invalid config param 8814

### ISSUE THREAD

**Issue by gonzoknows** [4rkal/MoneroOS#6]
Receiving this code upon startup

`B.4213731 and _gpio AMDI8838:8B: Invalid config param 8814
8.4214141 and_gpio AMDI0830:00: Invalid config param 8014
0.4214371 and _gpio AMD10830:00: Invalid config param 0014
0.4214611 and _gpio AMD10830:00: Invalid config param 8814
8.4214831 and _gpio ANDI0830:00: Invalid config param 0814
8.421506] and_gpio AMDI0830:00: Invalid config param 8814
8.4215291 amd_gpio AMDI0830:00: Invalid config param 8014
0.4215511 and gpio AMDI0830:00: Invalid config param 8814
0.421573] amd gpio AMD10030:00: Invalid config param 8814
8.4215971 and _gpio ADI0030:00: Invalid config param 8014`

**Comment by gonzoknows** [comment]
Also recieving this 

`4.811846] amdgpu 0BBO:06:00.0: amdgpu: Secure display: Generic Failure.
[
4.8118651 andgpu B80B:B6:00.O: amdypu: SECUREDISPLAY: query securedisplay T
A failed. ret 0x0`

**Comment by 4rkal** [comment]
Are these warnings or error messages? Does your device boot afterwards?

**Comment by gonzoknows** [comment]
> Are these warnings or error messages? Does your device boot afterwards?

It boots the screen but still have to set up internet permissions, so it gives an error, I'll report back when I use it on a device connected to Ethernet

**Comment by 4rkal** [comment]
Since this is just a warning I see no point in keeping this issue open. Graphics drivers are not needed to run MoneroOS.
